<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ticcmodel"
    nsURI="" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Ticc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="possède" upperBound="-1"
        eType="#//TiccElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TiccElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalVariable" eSuperTypes="#//TiccElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocalEtat"/>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//IOElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Local" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//IOElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//Transition"/>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalInput" eSuperTypes="#//Input">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//IOElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalInput" eSuperTypes="#//Input">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//IOElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//TiccElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//LocalVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localetat" upperBound="-1"
        eType="#//LocalEtat" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
