<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sequencemetamodel"
    nsURI="http://sequencemetamodel/1.0" nsPrefix="sequencemetamodel">
  <eClassifiers xsi:type="ecore:EClass" name="SequenceDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" lowerBound="1"
        upperBound="-1" eType="#//Sequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isComposed" lowerBound="1"
        upperBound="-1" eType="#//Part" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isComposedBy" lowerBound="1"
        upperBound="-1" eType="#//Message" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendTo" lowerBound="1"
        eType="#//Part" eOpposite="#//Part/sender"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveFrom" lowerBound="1"
        eType="#//Part" eOpposite="#//Part/receiver"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isCalled" lowerBound="1"
        eType="#//Method" eOpposite="#//Method/method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isA" lowerBound="1" eType="#//Corps"
        eOpposite="#//Corps/method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isDefinedBy" lowerBound="1"
        eType="#//TypeMessage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Part">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" upperBound="-1"
        eType="#//Message" eOpposite="#//Message/sendTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" upperBound="-1"
        eType="#//Message" eOpposite="#//Message/receiveFrom"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" upperBound="-1"
        eType="#//Method" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Corps"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method">
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
        eType="#//Message" eOpposite="#//Message/isCalled"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Corps">
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
        eType="#//Message" eOpposite="#//Message/isA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alt" eSuperTypes="#//TypeMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//TypeMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Seq" eSuperTypes="#//TypeMessage"/>
</ecore:EPackage>

